import { Manrope } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";


const manrope = Manrope({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en" className={manrope.className}>
        <body
          className="overflow-x-hidden"
        >
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
